add_collabs: >
  Next, we're going to add our other developers as collaborators on your
  repository so they can help track your progress.
create_client: >
  First we need to create a "personal access token" to access your GitHub
  account. To do so, we'll need your password and optionally a two-factor
  authorization code. You can find your personal access tokens at
  <%= color 'https://github.com/settings/tokens', :bold %>.
create_issues: >
  Now we're creating a milestone and issues in your copy of this repository
  on GitHub.
done: >
  All done! You're set to start training.
